### PR TITLE
Mod

### PR DESCRIPTION
**Pull request by RDIL**
some work on the mod

### CODE REVIEW

**Comment by MapleTheCoder** [comment]
Whoa this is pretty epic!

**Comment by RDIL** [comment]
I'll continue this tomorrow once I get some sleep

**Comment by MapleTheCoder** [comment]
YAY I should sleep too.

**Comment by MapleTheCoder** [comment]
Oh yea btw do I needa do somthing to this pull thing or whatever? Do I need to say like yes somewhere or am I good?

**Comment by RDIL** [comment]
@MapleTheCoder I actually do need you to do something:

Can you install Cirrus CI so every modification can be tested automatically?

Its free, just head [here](https://github.com/marketplace/cirrus-ci), select `Install it for free`, and then click all repositories.

**Comment by MapleTheCoder** [comment]
Awesome I will do. Can I do it on my phone rn? I can't get to my computer.

**Comment by RDIL** [comment]
Yup you can

**Comment by MapleTheCoder** [comment]
Okay I've done it I think!

**Comment by MapleTheCoder** [comment]
Okay I am sadly not compitent enough to setup the actual mod file and thus add it to my mods folder. But I did run it in the intelliJ thing. I think chat is broken.  https://hasteb.in/pafuxohi.rb

**Comment by MapleTheCoder** [comment]
eeek

**Comment by RDIL** [comment]
oh right i got to finish this

**Comment by RDIL** [comment]
whatever this should work i hope

**Pull request merged**
